config/routes.rb
Rails.application.routes.draw do
  root 'static_notes#home'

  get '/about', to: 'static_notes#about'

  resources :notes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def index
    @notes = Note.all #SEQUL of selct * from note
    #create @var and set equal to all of notes
  end

  def show
    #use a single page
    @note = Note.find(params[:id])
    #note.find is active reocrd equivalent
    #use params id because passing in paramet of id for form
  end

  def new
    #Note.create - this adds note to database
    @note = Note.new
    #totally separate instance var
    #stores new note in memory (not in database)
  end

  def create
    @note = Note.new(notes_params)
    #making new note in memory with notes params
    if @note.save
      redirect_to notes_path
    else
      render :new
    end
  end

  def edit
    @note = Note.find(params[:id])
  end

  def update
    @note = Note.find(params[:id])
    if @note.update(notes_params)
      redirect_to notes_path
    else
      render :edit
    end
  end

  def destroy
    Note.find(params[:id]).destroy
    redirect_to notes_path
  end

  private
    def notes_params
      params.require(:note).permit(:title, :author, :body)
    end
    # back end looks like {note: {title: 'foo', author: ...}}
    #note.new is created with the key value pairs with permit
end

app/controllers/static_notes_controller.rb
class StaticNotesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/static_notes_helper.rb
module StaticNotesHelper
end

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', root_path %>
<%= link_to 'About', about_path %>
<%= link_to 'Notes', notes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PostItNotes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/notes/edit.html.erb
<%= form_for @note do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :author %>
  <%= f.text_field :author %>

  <%= f.label :body %>
  <%= f.text_area :body %>

  <%= f.submit %>

<% end %>

app/views/notes/index.html.erb
<h1>My Notes</h1>

<% @notes.each do |note| %>
  <%= note.title %>
  <%= link_to 'Show Note', note_path(note) %>
  <%= link_to 'Edit Note', edit_note_path(note) %>
  <%= link_to 'Delete Note', note, method: :delete %>
  <% end %>

  <%= link_to 'New Note', new_note_path %>

app/views/notes/new.html.erb
<%= form_for @note do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label :body %>
  <%= f.text_area :body %>

  <%= f.submit %>

<% end %>

app/views/notes/show.html.erb
<%= @note.title %>
<%= @note.author %>
<%= @note.body %>

<%= link_to 'Back', notes_path %>

app/views/static_notes/about.html.erb
<h1>My About Notes</h1>

app/views/static_notes/home.html.erb
<h1>My Home Note</h1>